services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: creditcard
      POSTGRES_USER: cct_user
      POSTGRES_PASSWORD: cct_pass
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine
    restart: unless-stopped

  backend:
    build: ./backend_go
    depends_on:
      - db
      - redis
    environment:
      DATABASE_URL: postgres://cct_user:cct_pass@db:5432/creditcard?sslmode=disable
      REDIS_HOST: redis
      REDIS_PORT: 6379
      RUN_SEED: "1"
      SEED_DIR: "/seeddata"
      WAIT_FOR_DEPS: "1"
    volumes:
      - ./backend_go/db/seed:/seeddata:ro
    ports:
      - "3000:3000"

  frontend:
    build: ./frontend
    depends_on:
      - backend
    ports:
      - "5173:5173"

  nginx:
    image: nginx:stable
    depends_on:
      - frontend
      - backend
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - /opt/nginx/ssl:/etc/nginx/ssl:ro
    ports:
      - "80:80"
      - "443:443"

  jmeter:
    image: justb4/jmeter:5.4
    depends_on:
      - backend
    volumes:
      - ./loadtest/jmeter:/tests
    working_dir: /tests
    command:
      - -n
      - -t
      - /tests/test.jmx
      - -l
      - /tests/results/results.jtl
      - -e
      - -o
      - /tests/results/report

volumes:
  pgdata:
